/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InsightsApiModelsResponsesGenerationHalfHourlyInterconnectorOutturn
    /// </summary>
    [DataContract(Name = "Insights.Api.Models.Responses.Generation.HalfHourlyInterconnectorOutturn")]
    public partial class InsightsApiModelsResponsesGenerationHalfHourlyInterconnectorOutturn : IEquatable<InsightsApiModelsResponsesGenerationHalfHourlyInterconnectorOutturn>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InsightsApiModelsResponsesGenerationHalfHourlyInterconnectorOutturn" /> class.
        /// </summary>
        /// <param name="publishTime">publishTime.</param>
        /// <param name="startTime">startTime.</param>
        /// <param name="settlementDate">settlementDate.</param>
        /// <param name="settlementPeriod">settlementPeriod.</param>
        /// <param name="interconnectorName">interconnectorName.</param>
        /// <param name="generation">generation.</param>
        public InsightsApiModelsResponsesGenerationHalfHourlyInterconnectorOutturn(DateTime? publishTime = default(DateTime?), DateTime? startTime = default(DateTime?), DateTime settlementDate = default(DateTime), int? settlementPeriod = default(int?), string interconnectorName = default(string), long? generation = default(long?))
        {
            this.PublishTime = publishTime;
            this.StartTime = startTime;
            this.SettlementDate = settlementDate;
            this.SettlementPeriod = settlementPeriod;
            this.InterconnectorName = interconnectorName;
            this.Generation = generation;
        }

        /// <summary>
        /// Gets or Sets Dataset
        /// </summary>
        [DataMember(Name = "dataset", EmitDefaultValue = true)]
        public string Dataset { get; private set; }

        /// <summary>
        /// Returns false as Dataset should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDataset()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets PublishTime
        /// </summary>
        [DataMember(Name = "publishTime", EmitDefaultValue = true)]
        public DateTime? PublishTime { get; set; }

        /// <summary>
        /// Gets or Sets StartTime
        /// </summary>
        [DataMember(Name = "startTime", EmitDefaultValue = true)]
        public DateTime? StartTime { get; set; }

        /// <summary>
        /// Gets or Sets SettlementDate
        /// </summary>
        [DataMember(Name = "settlementDate", EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime SettlementDate { get; set; }

        /// <summary>
        /// Gets or Sets SettlementDateTimezone
        /// </summary>
        [DataMember(Name = "settlementDateTimezone", EmitDefaultValue = true)]
        public string SettlementDateTimezone { get; private set; }

        /// <summary>
        /// Returns false as SettlementDateTimezone should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSettlementDateTimezone()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets SettlementPeriod
        /// </summary>
        [DataMember(Name = "settlementPeriod", EmitDefaultValue = true)]
        public int? SettlementPeriod { get; set; }

        /// <summary>
        /// Gets or Sets InterconnectorName
        /// </summary>
        [DataMember(Name = "interconnectorName", EmitDefaultValue = true)]
        public string InterconnectorName { get; set; }

        /// <summary>
        /// Gets or Sets Generation
        /// </summary>
        [DataMember(Name = "generation", EmitDefaultValue = true)]
        public long? Generation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InsightsApiModelsResponsesGenerationHalfHourlyInterconnectorOutturn {\n");
            sb.Append("  Dataset: ").Append(Dataset).Append("\n");
            sb.Append("  PublishTime: ").Append(PublishTime).Append("\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  SettlementDate: ").Append(SettlementDate).Append("\n");
            sb.Append("  SettlementDateTimezone: ").Append(SettlementDateTimezone).Append("\n");
            sb.Append("  SettlementPeriod: ").Append(SettlementPeriod).Append("\n");
            sb.Append("  InterconnectorName: ").Append(InterconnectorName).Append("\n");
            sb.Append("  Generation: ").Append(Generation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InsightsApiModelsResponsesGenerationHalfHourlyInterconnectorOutturn);
        }

        /// <summary>
        /// Returns true if InsightsApiModelsResponsesGenerationHalfHourlyInterconnectorOutturn instances are equal
        /// </summary>
        /// <param name="input">Instance of InsightsApiModelsResponsesGenerationHalfHourlyInterconnectorOutturn to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InsightsApiModelsResponsesGenerationHalfHourlyInterconnectorOutturn input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Dataset == input.Dataset ||
                    (this.Dataset != null &&
                    this.Dataset.Equals(input.Dataset))
                ) && 
                (
                    this.PublishTime == input.PublishTime ||
                    (this.PublishTime != null &&
                    this.PublishTime.Equals(input.PublishTime))
                ) && 
                (
                    this.StartTime == input.StartTime ||
                    (this.StartTime != null &&
                    this.StartTime.Equals(input.StartTime))
                ) && 
                (
                    this.SettlementDate == input.SettlementDate ||
                    (this.SettlementDate != null &&
                    this.SettlementDate.Equals(input.SettlementDate))
                ) && 
                (
                    this.SettlementDateTimezone == input.SettlementDateTimezone ||
                    (this.SettlementDateTimezone != null &&
                    this.SettlementDateTimezone.Equals(input.SettlementDateTimezone))
                ) && 
                (
                    this.SettlementPeriod == input.SettlementPeriod ||
                    (this.SettlementPeriod != null &&
                    this.SettlementPeriod.Equals(input.SettlementPeriod))
                ) && 
                (
                    this.InterconnectorName == input.InterconnectorName ||
                    (this.InterconnectorName != null &&
                    this.InterconnectorName.Equals(input.InterconnectorName))
                ) && 
                (
                    this.Generation == input.Generation ||
                    (this.Generation != null &&
                    this.Generation.Equals(input.Generation))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Dataset != null)
                {
                    hashCode = (hashCode * 59) + this.Dataset.GetHashCode();
                }
                if (this.PublishTime != null)
                {
                    hashCode = (hashCode * 59) + this.PublishTime.GetHashCode();
                }
                if (this.StartTime != null)
                {
                    hashCode = (hashCode * 59) + this.StartTime.GetHashCode();
                }
                if (this.SettlementDate != null)
                {
                    hashCode = (hashCode * 59) + this.SettlementDate.GetHashCode();
                }
                if (this.SettlementDateTimezone != null)
                {
                    hashCode = (hashCode * 59) + this.SettlementDateTimezone.GetHashCode();
                }
                if (this.SettlementPeriod != null)
                {
                    hashCode = (hashCode * 59) + this.SettlementPeriod.GetHashCode();
                }
                if (this.InterconnectorName != null)
                {
                    hashCode = (hashCode * 59) + this.InterconnectorName.GetHashCode();
                }
                if (this.Generation != null)
                {
                    hashCode = (hashCode * 59) + this.Generation.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
