/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InsightsApiModelsResponsesMiscDatasetRowsSystemWarningsData
    /// </summary>
    [DataContract(Name = "Insights.Api.Models.Responses.Misc.DatasetRows.SystemWarningsData")]
    public partial class InsightsApiModelsResponsesMiscDatasetRowsSystemWarningsData : IEquatable<InsightsApiModelsResponsesMiscDatasetRowsSystemWarningsData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InsightsApiModelsResponsesMiscDatasetRowsSystemWarningsData" /> class.
        /// </summary>
        /// <param name="dataset">dataset.</param>
        /// <param name="publishTime">publishTime.</param>
        /// <param name="warningText">warningText.</param>
        public InsightsApiModelsResponsesMiscDatasetRowsSystemWarningsData(string dataset = default(string), DateTime? publishTime = default(DateTime?), string warningText = default(string))
        {
            this.Dataset = dataset;
            this.PublishTime = publishTime;
            this.WarningText = warningText;
        }

        /// <summary>
        /// Gets or Sets Dataset
        /// </summary>
        /// <example>SYSWARN</example>
        [DataMember(Name = "dataset", EmitDefaultValue = true)]
        public string Dataset { get; set; }

        /// <summary>
        /// Gets or Sets PublishTime
        /// </summary>
        /// <example>2022-09-20T00:00Z</example>
        [DataMember(Name = "publishTime", EmitDefaultValue = true)]
        public DateTime? PublishTime { get; set; }

        /// <summary>
        /// Gets or Sets WarningText
        /// </summary>
        /// <example>NATIONAL GRID NOTIFICATION of excess energy prices used for settlement outside of BALIT for SO to SO Transactions</example>
        [DataMember(Name = "warningText", EmitDefaultValue = true)]
        public string WarningText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InsightsApiModelsResponsesMiscDatasetRowsSystemWarningsData {\n");
            sb.Append("  Dataset: ").Append(Dataset).Append("\n");
            sb.Append("  PublishTime: ").Append(PublishTime).Append("\n");
            sb.Append("  WarningText: ").Append(WarningText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InsightsApiModelsResponsesMiscDatasetRowsSystemWarningsData);
        }

        /// <summary>
        /// Returns true if InsightsApiModelsResponsesMiscDatasetRowsSystemWarningsData instances are equal
        /// </summary>
        /// <param name="input">Instance of InsightsApiModelsResponsesMiscDatasetRowsSystemWarningsData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InsightsApiModelsResponsesMiscDatasetRowsSystemWarningsData input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Dataset == input.Dataset ||
                    (this.Dataset != null &&
                    this.Dataset.Equals(input.Dataset))
                ) && 
                (
                    this.PublishTime == input.PublishTime ||
                    (this.PublishTime != null &&
                    this.PublishTime.Equals(input.PublishTime))
                ) && 
                (
                    this.WarningText == input.WarningText ||
                    (this.WarningText != null &&
                    this.WarningText.Equals(input.WarningText))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Dataset != null)
                {
                    hashCode = (hashCode * 59) + this.Dataset.GetHashCode();
                }
                if (this.PublishTime != null)
                {
                    hashCode = (hashCode * 59) + this.PublishTime.GetHashCode();
                }
                if (this.WarningText != null)
                {
                    hashCode = (hashCode * 59) + this.WarningText.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
