/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing BidOfferApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BidOfferApiTests : IDisposable
    {
        private BidOfferApi instance;

        public BidOfferApiTests()
        {
            instance = new BidOfferApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BidOfferApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BidOfferApi
            //Assert.IsType<BidOfferApi>(instance);
        }

        /// <summary>
        /// Test BalancingBidOfferAllGet
        /// </summary>
        [Fact]
        public void BalancingBidOfferAllGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DateTime settlementDate = null;
            //int? settlementPeriod = null;
            //List<string>? bmUnit = null;
            //string? format = null;
            //var response = instance.BalancingBidOfferAllGet(settlementDate, settlementPeriod, bmUnit, format);
            //Assert.IsType<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingBidOfferResponse>(response);
        }

        /// <summary>
        /// Test BalancingBidOfferGet
        /// </summary>
        [Fact]
        public void BalancingBidOfferGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string bmUnit = null;
            //DateTime from = null;
            //DateTime to = null;
            //int? settlementPeriodFrom = null;
            //int? settlementPeriodTo = null;
            //string? format = null;
            //var response = instance.BalancingBidOfferGet(bmUnit, from, to, settlementPeriodFrom, settlementPeriodTo, format);
            //Assert.IsType<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingBidOfferResponse>(response);
        }
    }
}
