/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing MarginForecastApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MarginForecastApiTests : IDisposable
    {
        private MarginForecastApi instance;

        public MarginForecastApiTests()
        {
            instance = new MarginForecastApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MarginForecastApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MarginForecastApi
            //Assert.IsType<MarginForecastApi>(instance);
        }

        /// <summary>
        /// Test ForecastMarginDailyEvolutionGet
        /// </summary>
        [Fact]
        public void ForecastMarginDailyEvolutionGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DateTime forecastDate = null;
            //string? format = null;
            //var response = instance.ForecastMarginDailyEvolutionGet(forecastDate, format);
            //Assert.IsType<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesForecastMarginForecastMarginDaily>(response);
        }

        /// <summary>
        /// Test ForecastMarginDailyGet
        /// </summary>
        [Fact]
        public void ForecastMarginDailyGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? format = null;
            //var response = instance.ForecastMarginDailyGet(format);
            //Assert.IsType<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesForecastMarginForecastMarginDaily>(response);
        }

        /// <summary>
        /// Test ForecastMarginDailyHistoryGet
        /// </summary>
        [Fact]
        public void ForecastMarginDailyHistoryGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DateTime publishTime = null;
            //string? format = null;
            //var response = instance.ForecastMarginDailyHistoryGet(publishTime, format);
            //Assert.IsType<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesForecastMarginForecastMarginDaily>(response);
        }

        /// <summary>
        /// Test ForecastMarginWeeklyEvolutionGet
        /// </summary>
        [Fact]
        public void ForecastMarginWeeklyEvolutionGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int year = null;
            //int week = null;
            //string? range = null;
            //string? format = null;
            //var response = instance.ForecastMarginWeeklyEvolutionGet(year, week, range, format);
            //Assert.IsType<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesForecastMarginForecastMarginWeekly>(response);
        }

        /// <summary>
        /// Test ForecastMarginWeeklyGet
        /// </summary>
        [Fact]
        public void ForecastMarginWeeklyGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? range = null;
            //string? format = null;
            //var response = instance.ForecastMarginWeeklyGet(range, format);
            //Assert.IsType<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesForecastMarginForecastMarginWeekly>(response);
        }

        /// <summary>
        /// Test ForecastMarginWeeklyHistoryGet
        /// </summary>
        [Fact]
        public void ForecastMarginWeeklyHistoryGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DateTime publishTime = null;
            //string? range = null;
            //string? format = null;
            //var response = instance.ForecastMarginWeeklyHistoryGet(publishTime, range, format);
            //Assert.IsType<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesForecastMarginForecastMarginWeekly>(response);
        }
    }
}
