/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing SystemFrequencyApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SystemFrequencyApiTests : IDisposable
    {
        private SystemFrequencyApi instance;

        public SystemFrequencyApiTests()
        {
            instance = new SystemFrequencyApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SystemFrequencyApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SystemFrequencyApi
            //Assert.IsType<SystemFrequencyApi>(instance);
        }

        /// <summary>
        /// Test SystemFrequencyGet
        /// </summary>
        [Fact]
        public void SystemFrequencyGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DateTime? from = null;
            //DateTime? to = null;
            //string? format = null;
            //var response = instance.SystemFrequencyGet(from, to, format);
            //Assert.IsType<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesMiscSystemFrequency>(response);
        }

        /// <summary>
        /// Test SystemFrequencyStreamGet
        /// </summary>
        [Fact]
        public void SystemFrequencyStreamGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DateTime? from = null;
            //DateTime? to = null;
            //var response = instance.SystemFrequencyStreamGet(from, to);
            //Assert.IsType<List<InsightsApiModelsResponsesMiscSystemFrequency>>(response);
        }
    }
}
