/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INonBMSTORApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Non-BM STOR (NONBM) events
        /// </summary>
        /// <remarks>
        /// This endpoint provides data about the start of NGESO Short Term Operating Reserves (STOR) events. This is  activity that is outside of the Balancing Mechanism and takes place to meet the need to  increase generation or decrease demand. Each result has a non-zero generation value which was preceded by a zero  generation value.                By default, the before parameter filters the data by start time. If the settlementPeriodBefore parameter is  provided, the before parameter instead filters on settlement date, allowing for searching by start time or  settlement date &amp; settlement period.  Note: When filtering via settlement date, before is treated as a Date only, with the time being ignored. For  example, 2022-06-01T00:00Z and 2022-06-01T11:11Z are both treated as the settlement date 2022-06-01.                All Dates and DateTimes should be expressed as defined within  &lt;a href&#x3D;\&quot;https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 3339&lt;/a&gt;.                Some examples of date parameter combinations are shown below.                Filtering latest 3 events:                    /balancing/nonbm/stor/events?count&#x3D;3                Filtering latest 3 events before start time:                    /balancing/nonbm/stor/events?before&#x3D;2022-08-01T00:00Z&amp;count&#x3D;3                Filtering latest 3 events before settlement date and settlement period:                    /balancing/nonbm/stor/events?before&#x3D;2022-08-01T00:00Z&amp;settlementPeriodBefore&#x3D;48&amp;count&#x3D;3
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="count">The number of events to return.</param>
        /// <param name="before">If specified, filters events to those with a start time before or at the date, or a settlement date before the date if  settlementPeriodBefore is also specified.  If omitted, latest events are returned. (optional)</param>
        /// <param name="settlementPeriodBefore">Filters events to those with a settlement period before or at the value.  Before parameter must be specified if this is specified. (optional)</param>
        /// <param name="format">Response data format. Use json/xml to include metadata. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse</returns>
        InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse BalancingNonbmStorEventsGet(int count, DateTime? before = default(DateTime?), int? settlementPeriodBefore = default(int?), string? format = default(string?), int operationIndex = 0);

        /// <summary>
        /// Non-BM STOR (NONBM) events
        /// </summary>
        /// <remarks>
        /// This endpoint provides data about the start of NGESO Short Term Operating Reserves (STOR) events. This is  activity that is outside of the Balancing Mechanism and takes place to meet the need to  increase generation or decrease demand. Each result has a non-zero generation value which was preceded by a zero  generation value.                By default, the before parameter filters the data by start time. If the settlementPeriodBefore parameter is  provided, the before parameter instead filters on settlement date, allowing for searching by start time or  settlement date &amp; settlement period.  Note: When filtering via settlement date, before is treated as a Date only, with the time being ignored. For  example, 2022-06-01T00:00Z and 2022-06-01T11:11Z are both treated as the settlement date 2022-06-01.                All Dates and DateTimes should be expressed as defined within  &lt;a href&#x3D;\&quot;https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 3339&lt;/a&gt;.                Some examples of date parameter combinations are shown below.                Filtering latest 3 events:                    /balancing/nonbm/stor/events?count&#x3D;3                Filtering latest 3 events before start time:                    /balancing/nonbm/stor/events?before&#x3D;2022-08-01T00:00Z&amp;count&#x3D;3                Filtering latest 3 events before settlement date and settlement period:                    /balancing/nonbm/stor/events?before&#x3D;2022-08-01T00:00Z&amp;settlementPeriodBefore&#x3D;48&amp;count&#x3D;3
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="count">The number of events to return.</param>
        /// <param name="before">If specified, filters events to those with a start time before or at the date, or a settlement date before the date if  settlementPeriodBefore is also specified.  If omitted, latest events are returned. (optional)</param>
        /// <param name="settlementPeriodBefore">Filters events to those with a settlement period before or at the value.  Before parameter must be specified if this is specified. (optional)</param>
        /// <param name="format">Response data format. Use json/xml to include metadata. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse</returns>
        ApiResponse<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse> BalancingNonbmStorEventsGetWithHttpInfo(int count, DateTime? before = default(DateTime?), int? settlementPeriodBefore = default(int?), string? format = default(string?), int operationIndex = 0);
        /// <summary>
        /// Non-BM STOR (NONBM) time series
        /// </summary>
        /// <remarks>
        /// This endpoint provides data about the Short Term Operating Reserves (STOR) that have been made use of  by NGESO. This is activity that is outside of the Balancing Mechanism and takes place to meet the need to  increase generation or decrease demand.                By default, the from and to parameters filter the data by time inclusively. If the settlementPeriodFrom or  settlementPeriodTo parameters are provided, the corresponding from or to parameter instead filters on settlement  date, allowing for searching by a combination of time and/or settlement date &amp; settlement period.  Note: When filtering via settlement date, from/to are treated as Dates only, with the time being ignored. For  example, 2022-06-01T00:00Z and 2022-06-01T11:11Z are both treated as the settlement date 2022-06-01.                All Dates and DateTimes should be expressed as defined within  &lt;a href&#x3D;\&quot;https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 3339&lt;/a&gt;.                Some examples of date parameter combinations are shown below.                Filtering from start time to start time:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z                Filtering from start time to settlement date and period:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodTo&#x3D;1                Filtering from settlement date and period to start time:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodFrom&#x3D;1                Filtering from settlement date and period to settlement date and period:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodFrom&#x3D;1&amp;settlementPeriodTo&#x3D;1
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="from">The \&quot;from\&quot; start time or settlement date for the filter.</param>
        /// <param name="to">The \&quot;to\&quot; start time or settlement date for the filter.</param>
        /// <param name="settlementPeriodFrom">The \&quot;from\&quot; settlement period for the filter. This should be an integer from 1-50 inclusive. (optional)</param>
        /// <param name="settlementPeriodTo">The \&quot;to\&quot; settlement period for the filter. This should be an integer from 1-50 inclusive. (optional)</param>
        /// <param name="includeZero">Include data points with a generation of zero. (optional)</param>
        /// <param name="format">Response data format. Use json/xml to include metadata. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse</returns>
        InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse BalancingNonbmStorGet(DateTime from, DateTime to, int? settlementPeriodFrom = default(int?), int? settlementPeriodTo = default(int?), bool? includeZero = default(bool?), string? format = default(string?), int operationIndex = 0);

        /// <summary>
        /// Non-BM STOR (NONBM) time series
        /// </summary>
        /// <remarks>
        /// This endpoint provides data about the Short Term Operating Reserves (STOR) that have been made use of  by NGESO. This is activity that is outside of the Balancing Mechanism and takes place to meet the need to  increase generation or decrease demand.                By default, the from and to parameters filter the data by time inclusively. If the settlementPeriodFrom or  settlementPeriodTo parameters are provided, the corresponding from or to parameter instead filters on settlement  date, allowing for searching by a combination of time and/or settlement date &amp; settlement period.  Note: When filtering via settlement date, from/to are treated as Dates only, with the time being ignored. For  example, 2022-06-01T00:00Z and 2022-06-01T11:11Z are both treated as the settlement date 2022-06-01.                All Dates and DateTimes should be expressed as defined within  &lt;a href&#x3D;\&quot;https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 3339&lt;/a&gt;.                Some examples of date parameter combinations are shown below.                Filtering from start time to start time:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z                Filtering from start time to settlement date and period:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodTo&#x3D;1                Filtering from settlement date and period to start time:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodFrom&#x3D;1                Filtering from settlement date and period to settlement date and period:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodFrom&#x3D;1&amp;settlementPeriodTo&#x3D;1
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="from">The \&quot;from\&quot; start time or settlement date for the filter.</param>
        /// <param name="to">The \&quot;to\&quot; start time or settlement date for the filter.</param>
        /// <param name="settlementPeriodFrom">The \&quot;from\&quot; settlement period for the filter. This should be an integer from 1-50 inclusive. (optional)</param>
        /// <param name="settlementPeriodTo">The \&quot;to\&quot; settlement period for the filter. This should be an integer from 1-50 inclusive. (optional)</param>
        /// <param name="includeZero">Include data points with a generation of zero. (optional)</param>
        /// <param name="format">Response data format. Use json/xml to include metadata. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse</returns>
        ApiResponse<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse> BalancingNonbmStorGetWithHttpInfo(DateTime from, DateTime to, int? settlementPeriodFrom = default(int?), int? settlementPeriodTo = default(int?), bool? includeZero = default(bool?), string? format = default(string?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INonBMSTORApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Non-BM STOR (NONBM) events
        /// </summary>
        /// <remarks>
        /// This endpoint provides data about the start of NGESO Short Term Operating Reserves (STOR) events. This is  activity that is outside of the Balancing Mechanism and takes place to meet the need to  increase generation or decrease demand. Each result has a non-zero generation value which was preceded by a zero  generation value.                By default, the before parameter filters the data by start time. If the settlementPeriodBefore parameter is  provided, the before parameter instead filters on settlement date, allowing for searching by start time or  settlement date &amp; settlement period.  Note: When filtering via settlement date, before is treated as a Date only, with the time being ignored. For  example, 2022-06-01T00:00Z and 2022-06-01T11:11Z are both treated as the settlement date 2022-06-01.                All Dates and DateTimes should be expressed as defined within  &lt;a href&#x3D;\&quot;https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 3339&lt;/a&gt;.                Some examples of date parameter combinations are shown below.                Filtering latest 3 events:                    /balancing/nonbm/stor/events?count&#x3D;3                Filtering latest 3 events before start time:                    /balancing/nonbm/stor/events?before&#x3D;2022-08-01T00:00Z&amp;count&#x3D;3                Filtering latest 3 events before settlement date and settlement period:                    /balancing/nonbm/stor/events?before&#x3D;2022-08-01T00:00Z&amp;settlementPeriodBefore&#x3D;48&amp;count&#x3D;3
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="count">The number of events to return.</param>
        /// <param name="before">If specified, filters events to those with a start time before or at the date, or a settlement date before the date if  settlementPeriodBefore is also specified.  If omitted, latest events are returned. (optional)</param>
        /// <param name="settlementPeriodBefore">Filters events to those with a settlement period before or at the value.  Before parameter must be specified if this is specified. (optional)</param>
        /// <param name="format">Response data format. Use json/xml to include metadata. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse</returns>
        System.Threading.Tasks.Task<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse> BalancingNonbmStorEventsGetAsync(int count, DateTime? before = default(DateTime?), int? settlementPeriodBefore = default(int?), string? format = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Non-BM STOR (NONBM) events
        /// </summary>
        /// <remarks>
        /// This endpoint provides data about the start of NGESO Short Term Operating Reserves (STOR) events. This is  activity that is outside of the Balancing Mechanism and takes place to meet the need to  increase generation or decrease demand. Each result has a non-zero generation value which was preceded by a zero  generation value.                By default, the before parameter filters the data by start time. If the settlementPeriodBefore parameter is  provided, the before parameter instead filters on settlement date, allowing for searching by start time or  settlement date &amp; settlement period.  Note: When filtering via settlement date, before is treated as a Date only, with the time being ignored. For  example, 2022-06-01T00:00Z and 2022-06-01T11:11Z are both treated as the settlement date 2022-06-01.                All Dates and DateTimes should be expressed as defined within  &lt;a href&#x3D;\&quot;https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 3339&lt;/a&gt;.                Some examples of date parameter combinations are shown below.                Filtering latest 3 events:                    /balancing/nonbm/stor/events?count&#x3D;3                Filtering latest 3 events before start time:                    /balancing/nonbm/stor/events?before&#x3D;2022-08-01T00:00Z&amp;count&#x3D;3                Filtering latest 3 events before settlement date and settlement period:                    /balancing/nonbm/stor/events?before&#x3D;2022-08-01T00:00Z&amp;settlementPeriodBefore&#x3D;48&amp;count&#x3D;3
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="count">The number of events to return.</param>
        /// <param name="before">If specified, filters events to those with a start time before or at the date, or a settlement date before the date if  settlementPeriodBefore is also specified.  If omitted, latest events are returned. (optional)</param>
        /// <param name="settlementPeriodBefore">Filters events to those with a settlement period before or at the value.  Before parameter must be specified if this is specified. (optional)</param>
        /// <param name="format">Response data format. Use json/xml to include metadata. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse>> BalancingNonbmStorEventsGetWithHttpInfoAsync(int count, DateTime? before = default(DateTime?), int? settlementPeriodBefore = default(int?), string? format = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Non-BM STOR (NONBM) time series
        /// </summary>
        /// <remarks>
        /// This endpoint provides data about the Short Term Operating Reserves (STOR) that have been made use of  by NGESO. This is activity that is outside of the Balancing Mechanism and takes place to meet the need to  increase generation or decrease demand.                By default, the from and to parameters filter the data by time inclusively. If the settlementPeriodFrom or  settlementPeriodTo parameters are provided, the corresponding from or to parameter instead filters on settlement  date, allowing for searching by a combination of time and/or settlement date &amp; settlement period.  Note: When filtering via settlement date, from/to are treated as Dates only, with the time being ignored. For  example, 2022-06-01T00:00Z and 2022-06-01T11:11Z are both treated as the settlement date 2022-06-01.                All Dates and DateTimes should be expressed as defined within  &lt;a href&#x3D;\&quot;https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 3339&lt;/a&gt;.                Some examples of date parameter combinations are shown below.                Filtering from start time to start time:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z                Filtering from start time to settlement date and period:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodTo&#x3D;1                Filtering from settlement date and period to start time:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodFrom&#x3D;1                Filtering from settlement date and period to settlement date and period:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodFrom&#x3D;1&amp;settlementPeriodTo&#x3D;1
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="from">The \&quot;from\&quot; start time or settlement date for the filter.</param>
        /// <param name="to">The \&quot;to\&quot; start time or settlement date for the filter.</param>
        /// <param name="settlementPeriodFrom">The \&quot;from\&quot; settlement period for the filter. This should be an integer from 1-50 inclusive. (optional)</param>
        /// <param name="settlementPeriodTo">The \&quot;to\&quot; settlement period for the filter. This should be an integer from 1-50 inclusive. (optional)</param>
        /// <param name="includeZero">Include data points with a generation of zero. (optional)</param>
        /// <param name="format">Response data format. Use json/xml to include metadata. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse</returns>
        System.Threading.Tasks.Task<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse> BalancingNonbmStorGetAsync(DateTime from, DateTime to, int? settlementPeriodFrom = default(int?), int? settlementPeriodTo = default(int?), bool? includeZero = default(bool?), string? format = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Non-BM STOR (NONBM) time series
        /// </summary>
        /// <remarks>
        /// This endpoint provides data about the Short Term Operating Reserves (STOR) that have been made use of  by NGESO. This is activity that is outside of the Balancing Mechanism and takes place to meet the need to  increase generation or decrease demand.                By default, the from and to parameters filter the data by time inclusively. If the settlementPeriodFrom or  settlementPeriodTo parameters are provided, the corresponding from or to parameter instead filters on settlement  date, allowing for searching by a combination of time and/or settlement date &amp; settlement period.  Note: When filtering via settlement date, from/to are treated as Dates only, with the time being ignored. For  example, 2022-06-01T00:00Z and 2022-06-01T11:11Z are both treated as the settlement date 2022-06-01.                All Dates and DateTimes should be expressed as defined within  &lt;a href&#x3D;\&quot;https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 3339&lt;/a&gt;.                Some examples of date parameter combinations are shown below.                Filtering from start time to start time:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z                Filtering from start time to settlement date and period:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodTo&#x3D;1                Filtering from settlement date and period to start time:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodFrom&#x3D;1                Filtering from settlement date and period to settlement date and period:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodFrom&#x3D;1&amp;settlementPeriodTo&#x3D;1
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="from">The \&quot;from\&quot; start time or settlement date for the filter.</param>
        /// <param name="to">The \&quot;to\&quot; start time or settlement date for the filter.</param>
        /// <param name="settlementPeriodFrom">The \&quot;from\&quot; settlement period for the filter. This should be an integer from 1-50 inclusive. (optional)</param>
        /// <param name="settlementPeriodTo">The \&quot;to\&quot; settlement period for the filter. This should be an integer from 1-50 inclusive. (optional)</param>
        /// <param name="includeZero">Include data points with a generation of zero. (optional)</param>
        /// <param name="format">Response data format. Use json/xml to include metadata. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse>> BalancingNonbmStorGetWithHttpInfoAsync(DateTime from, DateTime to, int? settlementPeriodFrom = default(int?), int? settlementPeriodTo = default(int?), bool? includeZero = default(bool?), string? format = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INonBMSTORApi : INonBMSTORApiSync, INonBMSTORApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class NonBMSTORApi : INonBMSTORApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="NonBMSTORApi"/> class.
        /// </summary>
        /// <returns></returns>
        public NonBMSTORApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NonBMSTORApi"/> class.
        /// </summary>
        /// <returns></returns>
        public NonBMSTORApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NonBMSTORApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public NonBMSTORApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NonBMSTORApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public NonBMSTORApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Non-BM STOR (NONBM) events This endpoint provides data about the start of NGESO Short Term Operating Reserves (STOR) events. This is  activity that is outside of the Balancing Mechanism and takes place to meet the need to  increase generation or decrease demand. Each result has a non-zero generation value which was preceded by a zero  generation value.                By default, the before parameter filters the data by start time. If the settlementPeriodBefore parameter is  provided, the before parameter instead filters on settlement date, allowing for searching by start time or  settlement date &amp; settlement period.  Note: When filtering via settlement date, before is treated as a Date only, with the time being ignored. For  example, 2022-06-01T00:00Z and 2022-06-01T11:11Z are both treated as the settlement date 2022-06-01.                All Dates and DateTimes should be expressed as defined within  &lt;a href&#x3D;\&quot;https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 3339&lt;/a&gt;.                Some examples of date parameter combinations are shown below.                Filtering latest 3 events:                    /balancing/nonbm/stor/events?count&#x3D;3                Filtering latest 3 events before start time:                    /balancing/nonbm/stor/events?before&#x3D;2022-08-01T00:00Z&amp;count&#x3D;3                Filtering latest 3 events before settlement date and settlement period:                    /balancing/nonbm/stor/events?before&#x3D;2022-08-01T00:00Z&amp;settlementPeriodBefore&#x3D;48&amp;count&#x3D;3
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="count">The number of events to return.</param>
        /// <param name="before">If specified, filters events to those with a start time before or at the date, or a settlement date before the date if  settlementPeriodBefore is also specified.  If omitted, latest events are returned. (optional)</param>
        /// <param name="settlementPeriodBefore">Filters events to those with a settlement period before or at the value.  Before parameter must be specified if this is specified. (optional)</param>
        /// <param name="format">Response data format. Use json/xml to include metadata. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse</returns>
        public InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse BalancingNonbmStorEventsGet(int count, DateTime? before = default(DateTime?), int? settlementPeriodBefore = default(int?), string? format = default(string?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse> localVarResponse = BalancingNonbmStorEventsGetWithHttpInfo(count, before, settlementPeriodBefore, format);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Non-BM STOR (NONBM) events This endpoint provides data about the start of NGESO Short Term Operating Reserves (STOR) events. This is  activity that is outside of the Balancing Mechanism and takes place to meet the need to  increase generation or decrease demand. Each result has a non-zero generation value which was preceded by a zero  generation value.                By default, the before parameter filters the data by start time. If the settlementPeriodBefore parameter is  provided, the before parameter instead filters on settlement date, allowing for searching by start time or  settlement date &amp; settlement period.  Note: When filtering via settlement date, before is treated as a Date only, with the time being ignored. For  example, 2022-06-01T00:00Z and 2022-06-01T11:11Z are both treated as the settlement date 2022-06-01.                All Dates and DateTimes should be expressed as defined within  &lt;a href&#x3D;\&quot;https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 3339&lt;/a&gt;.                Some examples of date parameter combinations are shown below.                Filtering latest 3 events:                    /balancing/nonbm/stor/events?count&#x3D;3                Filtering latest 3 events before start time:                    /balancing/nonbm/stor/events?before&#x3D;2022-08-01T00:00Z&amp;count&#x3D;3                Filtering latest 3 events before settlement date and settlement period:                    /balancing/nonbm/stor/events?before&#x3D;2022-08-01T00:00Z&amp;settlementPeriodBefore&#x3D;48&amp;count&#x3D;3
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="count">The number of events to return.</param>
        /// <param name="before">If specified, filters events to those with a start time before or at the date, or a settlement date before the date if  settlementPeriodBefore is also specified.  If omitted, latest events are returned. (optional)</param>
        /// <param name="settlementPeriodBefore">Filters events to those with a settlement period before or at the value.  Before parameter must be specified if this is specified. (optional)</param>
        /// <param name="format">Response data format. Use json/xml to include metadata. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse</returns>
        public Org.OpenAPITools.Client.ApiResponse<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse> BalancingNonbmStorEventsGetWithHttpInfo(int count, DateTime? before = default(DateTime?), int? settlementPeriodBefore = default(int?), string? format = default(string?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/csv"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "count", count));
            if (before != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "before", before));
            }
            if (settlementPeriodBefore != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "settlementPeriodBefore", settlementPeriodBefore));
            }
            if (format != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "format", format));
            }

            localVarRequestOptions.Operation = "NonBMSTORApi.BalancingNonbmStorEventsGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse>("/balancing/nonbm/stor/events", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BalancingNonbmStorEventsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Non-BM STOR (NONBM) events This endpoint provides data about the start of NGESO Short Term Operating Reserves (STOR) events. This is  activity that is outside of the Balancing Mechanism and takes place to meet the need to  increase generation or decrease demand. Each result has a non-zero generation value which was preceded by a zero  generation value.                By default, the before parameter filters the data by start time. If the settlementPeriodBefore parameter is  provided, the before parameter instead filters on settlement date, allowing for searching by start time or  settlement date &amp; settlement period.  Note: When filtering via settlement date, before is treated as a Date only, with the time being ignored. For  example, 2022-06-01T00:00Z and 2022-06-01T11:11Z are both treated as the settlement date 2022-06-01.                All Dates and DateTimes should be expressed as defined within  &lt;a href&#x3D;\&quot;https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 3339&lt;/a&gt;.                Some examples of date parameter combinations are shown below.                Filtering latest 3 events:                    /balancing/nonbm/stor/events?count&#x3D;3                Filtering latest 3 events before start time:                    /balancing/nonbm/stor/events?before&#x3D;2022-08-01T00:00Z&amp;count&#x3D;3                Filtering latest 3 events before settlement date and settlement period:                    /balancing/nonbm/stor/events?before&#x3D;2022-08-01T00:00Z&amp;settlementPeriodBefore&#x3D;48&amp;count&#x3D;3
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="count">The number of events to return.</param>
        /// <param name="before">If specified, filters events to those with a start time before or at the date, or a settlement date before the date if  settlementPeriodBefore is also specified.  If omitted, latest events are returned. (optional)</param>
        /// <param name="settlementPeriodBefore">Filters events to those with a settlement period before or at the value.  Before parameter must be specified if this is specified. (optional)</param>
        /// <param name="format">Response data format. Use json/xml to include metadata. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse</returns>
        public async System.Threading.Tasks.Task<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse> BalancingNonbmStorEventsGetAsync(int count, DateTime? before = default(DateTime?), int? settlementPeriodBefore = default(int?), string? format = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse> localVarResponse = await BalancingNonbmStorEventsGetWithHttpInfoAsync(count, before, settlementPeriodBefore, format, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Non-BM STOR (NONBM) events This endpoint provides data about the start of NGESO Short Term Operating Reserves (STOR) events. This is  activity that is outside of the Balancing Mechanism and takes place to meet the need to  increase generation or decrease demand. Each result has a non-zero generation value which was preceded by a zero  generation value.                By default, the before parameter filters the data by start time. If the settlementPeriodBefore parameter is  provided, the before parameter instead filters on settlement date, allowing for searching by start time or  settlement date &amp; settlement period.  Note: When filtering via settlement date, before is treated as a Date only, with the time being ignored. For  example, 2022-06-01T00:00Z and 2022-06-01T11:11Z are both treated as the settlement date 2022-06-01.                All Dates and DateTimes should be expressed as defined within  &lt;a href&#x3D;\&quot;https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 3339&lt;/a&gt;.                Some examples of date parameter combinations are shown below.                Filtering latest 3 events:                    /balancing/nonbm/stor/events?count&#x3D;3                Filtering latest 3 events before start time:                    /balancing/nonbm/stor/events?before&#x3D;2022-08-01T00:00Z&amp;count&#x3D;3                Filtering latest 3 events before settlement date and settlement period:                    /balancing/nonbm/stor/events?before&#x3D;2022-08-01T00:00Z&amp;settlementPeriodBefore&#x3D;48&amp;count&#x3D;3
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="count">The number of events to return.</param>
        /// <param name="before">If specified, filters events to those with a start time before or at the date, or a settlement date before the date if  settlementPeriodBefore is also specified.  If omitted, latest events are returned. (optional)</param>
        /// <param name="settlementPeriodBefore">Filters events to those with a settlement period before or at the value.  Before parameter must be specified if this is specified. (optional)</param>
        /// <param name="format">Response data format. Use json/xml to include metadata. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse>> BalancingNonbmStorEventsGetWithHttpInfoAsync(int count, DateTime? before = default(DateTime?), int? settlementPeriodBefore = default(int?), string? format = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/csv"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "count", count));
            if (before != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "before", before));
            }
            if (settlementPeriodBefore != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "settlementPeriodBefore", settlementPeriodBefore));
            }
            if (format != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "format", format));
            }

            localVarRequestOptions.Operation = "NonBMSTORApi.BalancingNonbmStorEventsGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse>("/balancing/nonbm/stor/events", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BalancingNonbmStorEventsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Non-BM STOR (NONBM) time series This endpoint provides data about the Short Term Operating Reserves (STOR) that have been made use of  by NGESO. This is activity that is outside of the Balancing Mechanism and takes place to meet the need to  increase generation or decrease demand.                By default, the from and to parameters filter the data by time inclusively. If the settlementPeriodFrom or  settlementPeriodTo parameters are provided, the corresponding from or to parameter instead filters on settlement  date, allowing for searching by a combination of time and/or settlement date &amp; settlement period.  Note: When filtering via settlement date, from/to are treated as Dates only, with the time being ignored. For  example, 2022-06-01T00:00Z and 2022-06-01T11:11Z are both treated as the settlement date 2022-06-01.                All Dates and DateTimes should be expressed as defined within  &lt;a href&#x3D;\&quot;https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 3339&lt;/a&gt;.                Some examples of date parameter combinations are shown below.                Filtering from start time to start time:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z                Filtering from start time to settlement date and period:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodTo&#x3D;1                Filtering from settlement date and period to start time:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodFrom&#x3D;1                Filtering from settlement date and period to settlement date and period:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodFrom&#x3D;1&amp;settlementPeriodTo&#x3D;1
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="from">The \&quot;from\&quot; start time or settlement date for the filter.</param>
        /// <param name="to">The \&quot;to\&quot; start time or settlement date for the filter.</param>
        /// <param name="settlementPeriodFrom">The \&quot;from\&quot; settlement period for the filter. This should be an integer from 1-50 inclusive. (optional)</param>
        /// <param name="settlementPeriodTo">The \&quot;to\&quot; settlement period for the filter. This should be an integer from 1-50 inclusive. (optional)</param>
        /// <param name="includeZero">Include data points with a generation of zero. (optional)</param>
        /// <param name="format">Response data format. Use json/xml to include metadata. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse</returns>
        public InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse BalancingNonbmStorGet(DateTime from, DateTime to, int? settlementPeriodFrom = default(int?), int? settlementPeriodTo = default(int?), bool? includeZero = default(bool?), string? format = default(string?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse> localVarResponse = BalancingNonbmStorGetWithHttpInfo(from, to, settlementPeriodFrom, settlementPeriodTo, includeZero, format);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Non-BM STOR (NONBM) time series This endpoint provides data about the Short Term Operating Reserves (STOR) that have been made use of  by NGESO. This is activity that is outside of the Balancing Mechanism and takes place to meet the need to  increase generation or decrease demand.                By default, the from and to parameters filter the data by time inclusively. If the settlementPeriodFrom or  settlementPeriodTo parameters are provided, the corresponding from or to parameter instead filters on settlement  date, allowing for searching by a combination of time and/or settlement date &amp; settlement period.  Note: When filtering via settlement date, from/to are treated as Dates only, with the time being ignored. For  example, 2022-06-01T00:00Z and 2022-06-01T11:11Z are both treated as the settlement date 2022-06-01.                All Dates and DateTimes should be expressed as defined within  &lt;a href&#x3D;\&quot;https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 3339&lt;/a&gt;.                Some examples of date parameter combinations are shown below.                Filtering from start time to start time:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z                Filtering from start time to settlement date and period:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodTo&#x3D;1                Filtering from settlement date and period to start time:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodFrom&#x3D;1                Filtering from settlement date and period to settlement date and period:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodFrom&#x3D;1&amp;settlementPeriodTo&#x3D;1
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="from">The \&quot;from\&quot; start time or settlement date for the filter.</param>
        /// <param name="to">The \&quot;to\&quot; start time or settlement date for the filter.</param>
        /// <param name="settlementPeriodFrom">The \&quot;from\&quot; settlement period for the filter. This should be an integer from 1-50 inclusive. (optional)</param>
        /// <param name="settlementPeriodTo">The \&quot;to\&quot; settlement period for the filter. This should be an integer from 1-50 inclusive. (optional)</param>
        /// <param name="includeZero">Include data points with a generation of zero. (optional)</param>
        /// <param name="format">Response data format. Use json/xml to include metadata. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse</returns>
        public Org.OpenAPITools.Client.ApiResponse<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse> BalancingNonbmStorGetWithHttpInfo(DateTime from, DateTime to, int? settlementPeriodFrom = default(int?), int? settlementPeriodTo = default(int?), bool? includeZero = default(bool?), string? format = default(string?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/csv"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "from", from));
            localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "to", to));
            if (settlementPeriodFrom != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "settlementPeriodFrom", settlementPeriodFrom));
            }
            if (settlementPeriodTo != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "settlementPeriodTo", settlementPeriodTo));
            }
            if (includeZero != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "includeZero", includeZero));
            }
            if (format != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "format", format));
            }

            localVarRequestOptions.Operation = "NonBMSTORApi.BalancingNonbmStorGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse>("/balancing/nonbm/stor", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BalancingNonbmStorGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Non-BM STOR (NONBM) time series This endpoint provides data about the Short Term Operating Reserves (STOR) that have been made use of  by NGESO. This is activity that is outside of the Balancing Mechanism and takes place to meet the need to  increase generation or decrease demand.                By default, the from and to parameters filter the data by time inclusively. If the settlementPeriodFrom or  settlementPeriodTo parameters are provided, the corresponding from or to parameter instead filters on settlement  date, allowing for searching by a combination of time and/or settlement date &amp; settlement period.  Note: When filtering via settlement date, from/to are treated as Dates only, with the time being ignored. For  example, 2022-06-01T00:00Z and 2022-06-01T11:11Z are both treated as the settlement date 2022-06-01.                All Dates and DateTimes should be expressed as defined within  &lt;a href&#x3D;\&quot;https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 3339&lt;/a&gt;.                Some examples of date parameter combinations are shown below.                Filtering from start time to start time:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z                Filtering from start time to settlement date and period:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodTo&#x3D;1                Filtering from settlement date and period to start time:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodFrom&#x3D;1                Filtering from settlement date and period to settlement date and period:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodFrom&#x3D;1&amp;settlementPeriodTo&#x3D;1
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="from">The \&quot;from\&quot; start time or settlement date for the filter.</param>
        /// <param name="to">The \&quot;to\&quot; start time or settlement date for the filter.</param>
        /// <param name="settlementPeriodFrom">The \&quot;from\&quot; settlement period for the filter. This should be an integer from 1-50 inclusive. (optional)</param>
        /// <param name="settlementPeriodTo">The \&quot;to\&quot; settlement period for the filter. This should be an integer from 1-50 inclusive. (optional)</param>
        /// <param name="includeZero">Include data points with a generation of zero. (optional)</param>
        /// <param name="format">Response data format. Use json/xml to include metadata. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse</returns>
        public async System.Threading.Tasks.Task<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse> BalancingNonbmStorGetAsync(DateTime from, DateTime to, int? settlementPeriodFrom = default(int?), int? settlementPeriodTo = default(int?), bool? includeZero = default(bool?), string? format = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse> localVarResponse = await BalancingNonbmStorGetWithHttpInfoAsync(from, to, settlementPeriodFrom, settlementPeriodTo, includeZero, format, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Non-BM STOR (NONBM) time series This endpoint provides data about the Short Term Operating Reserves (STOR) that have been made use of  by NGESO. This is activity that is outside of the Balancing Mechanism and takes place to meet the need to  increase generation or decrease demand.                By default, the from and to parameters filter the data by time inclusively. If the settlementPeriodFrom or  settlementPeriodTo parameters are provided, the corresponding from or to parameter instead filters on settlement  date, allowing for searching by a combination of time and/or settlement date &amp; settlement period.  Note: When filtering via settlement date, from/to are treated as Dates only, with the time being ignored. For  example, 2022-06-01T00:00Z and 2022-06-01T11:11Z are both treated as the settlement date 2022-06-01.                All Dates and DateTimes should be expressed as defined within  &lt;a href&#x3D;\&quot;https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 3339&lt;/a&gt;.                Some examples of date parameter combinations are shown below.                Filtering from start time to start time:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z                Filtering from start time to settlement date and period:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodTo&#x3D;1                Filtering from settlement date and period to start time:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodFrom&#x3D;1                Filtering from settlement date and period to settlement date and period:                    /balancing/nonbm/stor?from&#x3D;2022-06-01T00:00Z&amp;to&#x3D;2022-07-01T00:00Z&amp;settlementPeriodFrom&#x3D;1&amp;settlementPeriodTo&#x3D;1
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="from">The \&quot;from\&quot; start time or settlement date for the filter.</param>
        /// <param name="to">The \&quot;to\&quot; start time or settlement date for the filter.</param>
        /// <param name="settlementPeriodFrom">The \&quot;from\&quot; settlement period for the filter. This should be an integer from 1-50 inclusive. (optional)</param>
        /// <param name="settlementPeriodTo">The \&quot;to\&quot; settlement period for the filter. This should be an integer from 1-50 inclusive. (optional)</param>
        /// <param name="includeZero">Include data points with a generation of zero. (optional)</param>
        /// <param name="format">Response data format. Use json/xml to include metadata. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse>> BalancingNonbmStorGetWithHttpInfoAsync(DateTime from, DateTime to, int? settlementPeriodFrom = default(int?), int? settlementPeriodTo = default(int?), bool? includeZero = default(bool?), string? format = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/csv"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "from", from));
            localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "to", to));
            if (settlementPeriodFrom != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "settlementPeriodFrom", settlementPeriodFrom));
            }
            if (settlementPeriodTo != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "settlementPeriodTo", settlementPeriodTo));
            }
            if (includeZero != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "includeZero", includeZero));
            }
            if (format != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "format", format));
            }

            localVarRequestOptions.Operation = "NonBMSTORApi.BalancingNonbmStorGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingNonBmStorResponse>("/balancing/nonbm/stor", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BalancingNonbmStorGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
