/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InsightsApiModelsResponsesReferenceInterconnectorData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsightsApiModelsResponsesReferenceInterconnectorDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsightsApiModelsResponsesReferenceInterconnectorData
        //private InsightsApiModelsResponsesReferenceInterconnectorData instance;

        public InsightsApiModelsResponsesReferenceInterconnectorDataTests()
        {
            // TODO uncomment below to create an instance of InsightsApiModelsResponsesReferenceInterconnectorData
            //instance = new InsightsApiModelsResponsesReferenceInterconnectorData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsightsApiModelsResponsesReferenceInterconnectorData
        /// </summary>
        [Fact]
        public void InsightsApiModelsResponsesReferenceInterconnectorDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsightsApiModelsResponsesReferenceInterconnectorData
            //Assert.IsType<InsightsApiModelsResponsesReferenceInterconnectorData>(instance);
        }

        /// <summary>
        /// Test the property 'InterconnectorId'
        /// </summary>
        [Fact]
        public void InterconnectorIdTest()
        {
            // TODO unit test for the property 'InterconnectorId'
        }

        /// <summary>
        /// Test the property 'InterconnectorName'
        /// </summary>
        [Fact]
        public void InterconnectorNameTest()
        {
            // TODO unit test for the property 'InterconnectorName'
        }

        /// <summary>
        /// Test the property 'InterconnectorBiddingZone'
        /// </summary>
        [Fact]
        public void InterconnectorBiddingZoneTest()
        {
            // TODO unit test for the property 'InterconnectorBiddingZone'
        }
    }
}
