/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityByBmUnitWeekly
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityByBmUnitWeeklyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityByBmUnitWeekly
        //private InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityByBmUnitWeekly instance;

        public InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityByBmUnitWeeklyTests()
        {
            // TODO uncomment below to create an instance of InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityByBmUnitWeekly
            //instance = new InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityByBmUnitWeekly();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityByBmUnitWeekly
        /// </summary>
        [Fact]
        public void InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityByBmUnitWeeklyInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityByBmUnitWeekly
            //Assert.IsType<InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityByBmUnitWeekly>(instance);
        }

        /// <summary>
        /// Test the property 'Dataset'
        /// </summary>
        [Fact]
        public void DatasetTest()
        {
            // TODO unit test for the property 'Dataset'
        }

        /// <summary>
        /// Test the property 'FuelType'
        /// </summary>
        [Fact]
        public void FuelTypeTest()
        {
            // TODO unit test for the property 'FuelType'
        }

        /// <summary>
        /// Test the property 'NationalGridBmUnit'
        /// </summary>
        [Fact]
        public void NationalGridBmUnitTest()
        {
            // TODO unit test for the property 'NationalGridBmUnit'
        }

        /// <summary>
        /// Test the property 'BmUnit'
        /// </summary>
        [Fact]
        public void BmUnitTest()
        {
            // TODO unit test for the property 'BmUnit'
        }

        /// <summary>
        /// Test the property 'PublishTime'
        /// </summary>
        [Fact]
        public void PublishTimeTest()
        {
            // TODO unit test for the property 'PublishTime'
        }

        /// <summary>
        /// Test the property 'Week'
        /// </summary>
        [Fact]
        public void WeekTest()
        {
            // TODO unit test for the property 'Week'
        }

        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }

        /// <summary>
        /// Test the property 'OutputUsable'
        /// </summary>
        [Fact]
        public void OutputUsableTest()
        {
            // TODO unit test for the property 'OutputUsable'
        }
    }
}
