/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InsightsApiModelsResponsesTransparencyAgptSummaryData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsightsApiModelsResponsesTransparencyAgptSummaryDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsightsApiModelsResponsesTransparencyAgptSummaryData
        //private InsightsApiModelsResponsesTransparencyAgptSummaryData instance;

        public InsightsApiModelsResponsesTransparencyAgptSummaryDataTests()
        {
            // TODO uncomment below to create an instance of InsightsApiModelsResponsesTransparencyAgptSummaryData
            //instance = new InsightsApiModelsResponsesTransparencyAgptSummaryData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsightsApiModelsResponsesTransparencyAgptSummaryData
        /// </summary>
        [Fact]
        public void InsightsApiModelsResponsesTransparencyAgptSummaryDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsightsApiModelsResponsesTransparencyAgptSummaryData
            //Assert.IsType<InsightsApiModelsResponsesTransparencyAgptSummaryData>(instance);
        }

        /// <summary>
        /// Test the property 'PsrType'
        /// </summary>
        [Fact]
        public void PsrTypeTest()
        {
            // TODO unit test for the property 'PsrType'
        }

        /// <summary>
        /// Test the property 'HalfHourUsage'
        /// </summary>
        [Fact]
        public void HalfHourUsageTest()
        {
            // TODO unit test for the property 'HalfHourUsage'
        }

        /// <summary>
        /// Test the property 'HalfHourPercentage'
        /// </summary>
        [Fact]
        public void HalfHourPercentageTest()
        {
            // TODO unit test for the property 'HalfHourPercentage'
        }

        /// <summary>
        /// Test the property 'TwentyFourHourUsage'
        /// </summary>
        [Fact]
        public void TwentyFourHourUsageTest()
        {
            // TODO unit test for the property 'TwentyFourHourUsage'
        }

        /// <summary>
        /// Test the property 'TwentyFourHourPercentage'
        /// </summary>
        [Fact]
        public void TwentyFourHourPercentageTest()
        {
            // TODO unit test for the property 'TwentyFourHourPercentage'
        }
    }
}
