/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod
        //private InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod instance;

        public InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriodTests()
        {
            // TODO uncomment below to create an instance of InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod
            //instance = new InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod
        /// </summary>
        [Fact]
        public void InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriodInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod
            //Assert.IsType<InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod>(instance);
        }

        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Fact]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }

        /// <summary>
        /// Test the property 'SettlementPeriod'
        /// </summary>
        [Fact]
        public void SettlementPeriodTest()
        {
            // TODO unit test for the property 'SettlementPeriod'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
