/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InsightsApiModelsResponsesMiscDatasetRowsSystemFrequency
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsightsApiModelsResponsesMiscDatasetRowsSystemFrequencyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsightsApiModelsResponsesMiscDatasetRowsSystemFrequency
        //private InsightsApiModelsResponsesMiscDatasetRowsSystemFrequency instance;

        public InsightsApiModelsResponsesMiscDatasetRowsSystemFrequencyTests()
        {
            // TODO uncomment below to create an instance of InsightsApiModelsResponsesMiscDatasetRowsSystemFrequency
            //instance = new InsightsApiModelsResponsesMiscDatasetRowsSystemFrequency();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsightsApiModelsResponsesMiscDatasetRowsSystemFrequency
        /// </summary>
        [Fact]
        public void InsightsApiModelsResponsesMiscDatasetRowsSystemFrequencyInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsightsApiModelsResponsesMiscDatasetRowsSystemFrequency
            //Assert.IsType<InsightsApiModelsResponsesMiscDatasetRowsSystemFrequency>(instance);
        }

        /// <summary>
        /// Test the property 'Dataset'
        /// </summary>
        [Fact]
        public void DatasetTest()
        {
            // TODO unit test for the property 'Dataset'
        }

        /// <summary>
        /// Test the property 'MeasurementTime'
        /// </summary>
        [Fact]
        public void MeasurementTimeTest()
        {
            // TODO unit test for the property 'MeasurementTime'
        }

        /// <summary>
        /// Test the property 'Frequency'
        /// </summary>
        [Fact]
        public void FrequencyTest()
        {
            // TODO unit test for the property 'Frequency'
        }
    }
}
