/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InsightsApiModelsResponsesTransparencyRemitRemitMessageIdentifierWithUrl
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsightsApiModelsResponsesTransparencyRemitRemitMessageIdentifierWithUrlTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsightsApiModelsResponsesTransparencyRemitRemitMessageIdentifierWithUrl
        //private InsightsApiModelsResponsesTransparencyRemitRemitMessageIdentifierWithUrl instance;

        public InsightsApiModelsResponsesTransparencyRemitRemitMessageIdentifierWithUrlTests()
        {
            // TODO uncomment below to create an instance of InsightsApiModelsResponsesTransparencyRemitRemitMessageIdentifierWithUrl
            //instance = new InsightsApiModelsResponsesTransparencyRemitRemitMessageIdentifierWithUrl();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsightsApiModelsResponsesTransparencyRemitRemitMessageIdentifierWithUrl
        /// </summary>
        [Fact]
        public void InsightsApiModelsResponsesTransparencyRemitRemitMessageIdentifierWithUrlInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsightsApiModelsResponsesTransparencyRemitRemitMessageIdentifierWithUrl
            //Assert.IsType<InsightsApiModelsResponsesTransparencyRemitRemitMessageIdentifierWithUrl>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Mrid'
        /// </summary>
        [Fact]
        public void MridTest()
        {
            // TODO unit test for the property 'Mrid'
        }

        /// <summary>
        /// Test the property 'RevisionNumber'
        /// </summary>
        [Fact]
        public void RevisionNumberTest()
        {
            // TODO unit test for the property 'RevisionNumber'
        }

        /// <summary>
        /// Test the property 'CreatedTime'
        /// </summary>
        [Fact]
        public void CreatedTimeTest()
        {
            // TODO unit test for the property 'CreatedTime'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
