/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InsightsApiModelsResponsesForecastMarginDatasetRowsForecastMarginWeekly
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsightsApiModelsResponsesForecastMarginDatasetRowsForecastMarginWeeklyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsightsApiModelsResponsesForecastMarginDatasetRowsForecastMarginWeekly
        //private InsightsApiModelsResponsesForecastMarginDatasetRowsForecastMarginWeekly instance;

        public InsightsApiModelsResponsesForecastMarginDatasetRowsForecastMarginWeeklyTests()
        {
            // TODO uncomment below to create an instance of InsightsApiModelsResponsesForecastMarginDatasetRowsForecastMarginWeekly
            //instance = new InsightsApiModelsResponsesForecastMarginDatasetRowsForecastMarginWeekly();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsightsApiModelsResponsesForecastMarginDatasetRowsForecastMarginWeekly
        /// </summary>
        [Fact]
        public void InsightsApiModelsResponsesForecastMarginDatasetRowsForecastMarginWeeklyInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsightsApiModelsResponsesForecastMarginDatasetRowsForecastMarginWeekly
            //Assert.IsType<InsightsApiModelsResponsesForecastMarginDatasetRowsForecastMarginWeekly>(instance);
        }

        /// <summary>
        /// Test the property 'Dataset'
        /// </summary>
        [Fact]
        public void DatasetTest()
        {
            // TODO unit test for the property 'Dataset'
        }

        /// <summary>
        /// Test the property 'PublishTime'
        /// </summary>
        [Fact]
        public void PublishTimeTest()
        {
            // TODO unit test for the property 'PublishTime'
        }

        /// <summary>
        /// Test the property 'Week'
        /// </summary>
        [Fact]
        public void WeekTest()
        {
            // TODO unit test for the property 'Week'
        }

        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }

        /// <summary>
        /// Test the property 'Margin'
        /// </summary>
        [Fact]
        public void MarginTest()
        {
            // TODO unit test for the property 'Margin'
        }
    }
}
