/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InsightsApiModelsResponsesTransparencyRemitDatasetRowsOutageProfileData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsightsApiModelsResponsesTransparencyRemitDatasetRowsOutageProfileDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsightsApiModelsResponsesTransparencyRemitDatasetRowsOutageProfileData
        //private InsightsApiModelsResponsesTransparencyRemitDatasetRowsOutageProfileData instance;

        public InsightsApiModelsResponsesTransparencyRemitDatasetRowsOutageProfileDataTests()
        {
            // TODO uncomment below to create an instance of InsightsApiModelsResponsesTransparencyRemitDatasetRowsOutageProfileData
            //instance = new InsightsApiModelsResponsesTransparencyRemitDatasetRowsOutageProfileData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsightsApiModelsResponsesTransparencyRemitDatasetRowsOutageProfileData
        /// </summary>
        [Fact]
        public void InsightsApiModelsResponsesTransparencyRemitDatasetRowsOutageProfileDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsightsApiModelsResponsesTransparencyRemitDatasetRowsOutageProfileData
            //Assert.IsType<InsightsApiModelsResponsesTransparencyRemitDatasetRowsOutageProfileData>(instance);
        }

        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Fact]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }

        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Fact]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }

        /// <summary>
        /// Test the property 'Capacity'
        /// </summary>
        [Fact]
        public void CapacityTest()
        {
            // TODO unit test for the property 'Capacity'
        }
    }
}
