/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InsightsApiModelsResponsesTransparencyDatasetRowsIgcaDatasetRow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsightsApiModelsResponsesTransparencyDatasetRowsIgcaDatasetRowTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsightsApiModelsResponsesTransparencyDatasetRowsIgcaDatasetRow
        //private InsightsApiModelsResponsesTransparencyDatasetRowsIgcaDatasetRow instance;

        public InsightsApiModelsResponsesTransparencyDatasetRowsIgcaDatasetRowTests()
        {
            // TODO uncomment below to create an instance of InsightsApiModelsResponsesTransparencyDatasetRowsIgcaDatasetRow
            //instance = new InsightsApiModelsResponsesTransparencyDatasetRowsIgcaDatasetRow();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsightsApiModelsResponsesTransparencyDatasetRowsIgcaDatasetRow
        /// </summary>
        [Fact]
        public void InsightsApiModelsResponsesTransparencyDatasetRowsIgcaDatasetRowInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsightsApiModelsResponsesTransparencyDatasetRowsIgcaDatasetRow
            //Assert.IsType<InsightsApiModelsResponsesTransparencyDatasetRowsIgcaDatasetRow>(instance);
        }

        /// <summary>
        /// Test the property 'Dataset'
        /// </summary>
        [Fact]
        public void DatasetTest()
        {
            // TODO unit test for the property 'Dataset'
        }

        /// <summary>
        /// Test the property 'DocumentId'
        /// </summary>
        [Fact]
        public void DocumentIdTest()
        {
            // TODO unit test for the property 'DocumentId'
        }

        /// <summary>
        /// Test the property 'DocumentRevisionNumber'
        /// </summary>
        [Fact]
        public void DocumentRevisionNumberTest()
        {
            // TODO unit test for the property 'DocumentRevisionNumber'
        }

        /// <summary>
        /// Test the property 'PublishTime'
        /// </summary>
        [Fact]
        public void PublishTimeTest()
        {
            // TODO unit test for the property 'PublishTime'
        }

        /// <summary>
        /// Test the property 'BusinessType'
        /// </summary>
        [Fact]
        public void BusinessTypeTest()
        {
            // TODO unit test for the property 'BusinessType'
        }

        /// <summary>
        /// Test the property 'PsrType'
        /// </summary>
        [Fact]
        public void PsrTypeTest()
        {
            // TODO unit test for the property 'PsrType'
        }

        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
    }
}
