/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityDaily
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityDailyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityDaily
        //private InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityDaily instance;

        public InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityDailyTests()
        {
            // TODO uncomment below to create an instance of InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityDaily
            //instance = new InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityDaily();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityDaily
        /// </summary>
        [Fact]
        public void InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityDailyInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityDaily
            //Assert.IsType<InsightsApiModelsResponsesGenerationDatasetRowsAvailabilityDaily>(instance);
        }

        /// <summary>
        /// Test the property 'Dataset'
        /// </summary>
        [Fact]
        public void DatasetTest()
        {
            // TODO unit test for the property 'Dataset'
        }

        /// <summary>
        /// Test the property 'PublishTime'
        /// </summary>
        [Fact]
        public void PublishTimeTest()
        {
            // TODO unit test for the property 'PublishTime'
        }

        /// <summary>
        /// Test the property 'SystemZone'
        /// </summary>
        [Fact]
        public void SystemZoneTest()
        {
            // TODO unit test for the property 'SystemZone'
        }

        /// <summary>
        /// Test the property 'ForecastDate'
        /// </summary>
        [Fact]
        public void ForecastDateTest()
        {
            // TODO unit test for the property 'ForecastDate'
        }

        /// <summary>
        /// Test the property 'ForecastDateTimezone'
        /// </summary>
        [Fact]
        public void ForecastDateTimezoneTest()
        {
            // TODO unit test for the property 'ForecastDateTimezone'
        }

        /// <summary>
        /// Test the property 'OutputUsable'
        /// </summary>
        [Fact]
        public void OutputUsableTest()
        {
            // TODO unit test for the property 'OutputUsable'
        }
    }
}
