/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InsightsApiModelsResponsesForecastMarginForecastMarginDaily
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsightsApiModelsResponsesForecastMarginForecastMarginDailyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsightsApiModelsResponsesForecastMarginForecastMarginDaily
        //private InsightsApiModelsResponsesForecastMarginForecastMarginDaily instance;

        public InsightsApiModelsResponsesForecastMarginForecastMarginDailyTests()
        {
            // TODO uncomment below to create an instance of InsightsApiModelsResponsesForecastMarginForecastMarginDaily
            //instance = new InsightsApiModelsResponsesForecastMarginForecastMarginDaily();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsightsApiModelsResponsesForecastMarginForecastMarginDaily
        /// </summary>
        [Fact]
        public void InsightsApiModelsResponsesForecastMarginForecastMarginDailyInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsightsApiModelsResponsesForecastMarginForecastMarginDaily
            //Assert.IsType<InsightsApiModelsResponsesForecastMarginForecastMarginDaily>(instance);
        }

        /// <summary>
        /// Test the property 'PublishTime'
        /// </summary>
        [Fact]
        public void PublishTimeTest()
        {
            // TODO unit test for the property 'PublishTime'
        }

        /// <summary>
        /// Test the property 'Margin'
        /// </summary>
        [Fact]
        public void MarginTest()
        {
            // TODO unit test for the property 'Margin'
        }

        /// <summary>
        /// Test the property 'ForecastDate'
        /// </summary>
        [Fact]
        public void ForecastDateTest()
        {
            // TODO unit test for the property 'ForecastDate'
        }
    }
}
