/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse
        //private InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse instance;

        public InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponseTests()
        {
            // TODO uncomment below to create an instance of InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse
            //instance = new InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse
        /// </summary>
        [Fact]
        public void InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse
            //Assert.IsType<InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse>(instance);
        }

        /// <summary>
        /// Test the property 'SettlementDate'
        /// </summary>
        [Fact]
        public void SettlementDateTest()
        {
            // TODO unit test for the property 'SettlementDate'
        }

        /// <summary>
        /// Test the property 'SettlementPeriod'
        /// </summary>
        [Fact]
        public void SettlementPeriodTest()
        {
            // TODO unit test for the property 'SettlementPeriod'
        }

        /// <summary>
        /// Test the property 'MessageReceivedDateTime'
        /// </summary>
        [Fact]
        public void MessageReceivedDateTimeTest()
        {
            // TODO unit test for the property 'MessageReceivedDateTime'
        }

        /// <summary>
        /// Test the property 'MessageSeverity'
        /// </summary>
        [Fact]
        public void MessageSeverityTest()
        {
            // TODO unit test for the property 'MessageSeverity'
        }

        /// <summary>
        /// Test the property 'MessageType'
        /// </summary>
        [Fact]
        public void MessageTypeTest()
        {
            // TODO unit test for the property 'MessageType'
        }

        /// <summary>
        /// Test the property 'MessageText'
        /// </summary>
        [Fact]
        public void MessageTextTest()
        {
            // TODO unit test for the property 'MessageText'
        }
    }
}
