/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InsightsApiModelsResponsesGenerationAggregatedForecast
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsightsApiModelsResponsesGenerationAggregatedForecastTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsightsApiModelsResponsesGenerationAggregatedForecast
        //private InsightsApiModelsResponsesGenerationAggregatedForecast instance;

        public InsightsApiModelsResponsesGenerationAggregatedForecastTests()
        {
            // TODO uncomment below to create an instance of InsightsApiModelsResponsesGenerationAggregatedForecast
            //instance = new InsightsApiModelsResponsesGenerationAggregatedForecast();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsightsApiModelsResponsesGenerationAggregatedForecast
        /// </summary>
        [Fact]
        public void InsightsApiModelsResponsesGenerationAggregatedForecastInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsightsApiModelsResponsesGenerationAggregatedForecast
            //Assert.IsType<InsightsApiModelsResponsesGenerationAggregatedForecast>(instance);
        }

        /// <summary>
        /// Test the property 'ForecastDate'
        /// </summary>
        [Fact]
        public void ForecastDateTest()
        {
            // TODO unit test for the property 'ForecastDate'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
