/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InsightsApiModelsResponsesBalancingDynamicDatasetRowsDeliveryVolumeMaxData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsightsApiModelsResponsesBalancingDynamicDatasetRowsDeliveryVolumeMaxDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsightsApiModelsResponsesBalancingDynamicDatasetRowsDeliveryVolumeMaxData
        //private InsightsApiModelsResponsesBalancingDynamicDatasetRowsDeliveryVolumeMaxData instance;

        public InsightsApiModelsResponsesBalancingDynamicDatasetRowsDeliveryVolumeMaxDataTests()
        {
            // TODO uncomment below to create an instance of InsightsApiModelsResponsesBalancingDynamicDatasetRowsDeliveryVolumeMaxData
            //instance = new InsightsApiModelsResponsesBalancingDynamicDatasetRowsDeliveryVolumeMaxData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsightsApiModelsResponsesBalancingDynamicDatasetRowsDeliveryVolumeMaxData
        /// </summary>
        [Fact]
        public void InsightsApiModelsResponsesBalancingDynamicDatasetRowsDeliveryVolumeMaxDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsightsApiModelsResponsesBalancingDynamicDatasetRowsDeliveryVolumeMaxData
            //Assert.IsType<InsightsApiModelsResponsesBalancingDynamicDatasetRowsDeliveryVolumeMaxData>(instance);
        }

        /// <summary>
        /// Test the property 'Dataset'
        /// </summary>
        [Fact]
        public void DatasetTest()
        {
            // TODO unit test for the property 'Dataset'
        }

        /// <summary>
        /// Test the property 'SettlementDate'
        /// </summary>
        [Fact]
        public void SettlementDateTest()
        {
            // TODO unit test for the property 'SettlementDate'
        }

        /// <summary>
        /// Test the property 'SettlementPeriod'
        /// </summary>
        [Fact]
        public void SettlementPeriodTest()
        {
            // TODO unit test for the property 'SettlementPeriod'
        }

        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Fact]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }

        /// <summary>
        /// Test the property 'VolumeMax'
        /// </summary>
        [Fact]
        public void VolumeMaxTest()
        {
            // TODO unit test for the property 'VolumeMax'
        }

        /// <summary>
        /// Test the property 'NationalGridBmUnit'
        /// </summary>
        [Fact]
        public void NationalGridBmUnitTest()
        {
            // TODO unit test for the property 'NationalGridBmUnit'
        }

        /// <summary>
        /// Test the property 'BmUnit'
        /// </summary>
        [Fact]
        public void BmUnitTest()
        {
            // TODO unit test for the property 'BmUnit'
        }
    }
}
