/*
 * Insights.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InsightsApiModelsResponsesBalancingDatasetRowsMarketIndexDatasetResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsightsApiModelsResponsesBalancingDatasetRowsMarketIndexDatasetResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsightsApiModelsResponsesBalancingDatasetRowsMarketIndexDatasetResponse
        //private InsightsApiModelsResponsesBalancingDatasetRowsMarketIndexDatasetResponse instance;

        public InsightsApiModelsResponsesBalancingDatasetRowsMarketIndexDatasetResponseTests()
        {
            // TODO uncomment below to create an instance of InsightsApiModelsResponsesBalancingDatasetRowsMarketIndexDatasetResponse
            //instance = new InsightsApiModelsResponsesBalancingDatasetRowsMarketIndexDatasetResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsightsApiModelsResponsesBalancingDatasetRowsMarketIndexDatasetResponse
        /// </summary>
        [Fact]
        public void InsightsApiModelsResponsesBalancingDatasetRowsMarketIndexDatasetResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsightsApiModelsResponsesBalancingDatasetRowsMarketIndexDatasetResponse
            //Assert.IsType<InsightsApiModelsResponsesBalancingDatasetRowsMarketIndexDatasetResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Dataset'
        /// </summary>
        [Fact]
        public void DatasetTest()
        {
            // TODO unit test for the property 'Dataset'
        }

        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Fact]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }

        /// <summary>
        /// Test the property 'DataProvider'
        /// </summary>
        [Fact]
        public void DataProviderTest()
        {
            // TODO unit test for the property 'DataProvider'
        }

        /// <summary>
        /// Test the property 'SettlementDate'
        /// </summary>
        [Fact]
        public void SettlementDateTest()
        {
            // TODO unit test for the property 'SettlementDate'
        }

        /// <summary>
        /// Test the property 'SettlementPeriod'
        /// </summary>
        [Fact]
        public void SettlementPeriodTest()
        {
            // TODO unit test for the property 'SettlementPeriod'
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

        /// <summary>
        /// Test the property 'Volume'
        /// </summary>
        [Fact]
        public void VolumeTest()
        {
            // TODO unit test for the property 'Volume'
        }
    }
}
